### ISSUE TITLE
Support Reports API

### ISSUE THREAD

**Issue by fsargent** [MediaMath/t1-node#36]
https://github.com/AgencyPMG/node-mediamath/issues/3

The Reporting API should be covered within this SDK.

**Comment by ChrisAlvares** [comment]
Any updates to this? We want to switch over to the new api, but it has been over two months since the last commit.

**Comment by dearcodes** [comment]
+1 Any updates?

**Comment by FodT** [comment]
@dearcodes @ChrisAlvares we just merged reporting functionality to master :)
