### ISSUE TITLE
Trying to use Limit param fails

### ISSUE THREAD

**Issue by dearcodes** [MediaMath/t1-node#38]
I'm trying to limit a campaign EntityList query 

```
import t1 from '@mediamath/terminalone';

export function getCampaigns(connection, params = {}) {
  return new Promise((resolve, reject) => {
    let campaigns = [];
    let userParams = {
      limit: {
        advertiser_id: `${parseInt(params.advertiserId)}`,
      },
    };
    t1.EntityList.get('campaigns', connection, userParams).then(function(list) {
      for (let entity of list.entities) {
        campaigns.push(entity);
      }
      resolve(campaigns);
    });
  });
}

export default {
  getCampaigns,
};
```

and getting this error:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: instance does not match allOf schema </allEndpoints> with 1 error[s]:,instance.limit additionalProperty "advertiser_id" exists in instance when not allowed`

Any clue why this happens?

Thanks in advanced.

D.

**Comment by FodT** [comment]
hey @dearcodes, 

I can't be sure but looks like the value of params.advertiserId is 'advertiser_id' rather than an integer. Can you check?

**Comment by FodT** [comment]
The regex for the limit value excludes the '_' character - you should use the same string values as you'd use in the actual URL when constructing a limited query. e.g `advertiser.agency=1234`

**Comment by dearcodes** [comment]
@FodT Already tried that but didn't work:

`Error: instance does not match allOf schema </allEndpoints> with 1 error[s]:,instance.limit.advertiser is not of a type(s) integer`

It's weird because I'm parsing the string of params advertiserId to Integer.

Any clues?
