### ISSUE TITLE
t1-node 0.6.1 Config.apiBaseUrl causes GET/POST issues

### ISSUE THREAD

**Issue by seanhan-mediamath** [MediaMath/t1-node#49]
Tried to do a /GET using t1-node (v 0.6.1) for pixel_bundles and it made the request to api.mediamath.compixel_bundles. This uncovered a few issues below... 

1) Config.apiBaseUrl is 'https://api.mediamath.com' but the '/api/v2.0/' only gets added for T1Connection.prototype.ensureAuthenticated. This causes issues with T1Connection.prototype.get and T1Connection.prototype.post, when they try to build options.url resulting in requests such as api.mediamath.compixel_bundles. To get it working, I did a quick fix though via hipchat with Fod he mentioned the right way is to use entityMap:
a) updated Config.apiBaseUrl to "https://api.mediamath.com/api/v2.0/"
b) updated options.url built in T1Connection.prototype.ensureAuthenticated to be url: that.t1config.apiBaseUrl + "/login"

2) Related issue in EntityList.getNextPage, it's referencing a nonexistent property of 'Config'. 
var nextPage = retrievedNext.substring(Config.apiUrl.length, retrievedNext.length); 
needs to be
var nextPage = retrievedNext.substring(Config.apiBaseUrl.length, retrievedNext.length); 

3) Also related is that EntityList.getNextPage relies on EntityList.get, but EntityList.get is not a good friend :( 

Specifically this: var queryString = connection.buildQueryString(baseUrl, userParams);

As written, baseUrl for an initial EntityList.get is an entity name like 'strategies' or 'pixel_bundles'. And connection.buildQueryString builds the string out. However when EntityList.getNextPage calls Entitylist.get, it doesn't only pass the entity name as baseUrl, it passes a path + query string (with critical parameters such as page_offset)

pixel_bundles/limit/advertiser=149635?api_key=v4ps7ahp7rube6bvw79w8sgs&full=*&page_limit=100&page_offset=100&q=status%3D%3D1?api_key=v4ps7ahp7rube6bvw79w8sgs

An earlier version of of t1-node had a ternary which solves this:
var queryString = /^[a-z_]*$/.test(baseUrl) ?  connection.buildQueryString(baseUrl, userParams) : baseUrl;

**Comment by FodT** [comment]
hey @seanhan-mediamath, thanks for this! Yeah you're right; EntityList is pretty broken right now. I'll work on fixing this!

**Comment by FodT** [comment]
Fixed by #52
