### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames: "Host: sso.mediamath.auth0.com. is not in the cert's altnames: DNS:*.auth0.com, DNS:*.pus2.auth0.com"

### ISSUE THREAD

**Issue by ilomax** [MediaMath/t1-node#71]
Hello, when trying to use `connection.getOauthToken()`, I get the following error in return:
`Error: Hostname/IP doesn't match certificate's altnames: "Host: sso.mediamath.auth0.com. is not in the cert's altnames: DNS:*.auth0.com, DNS:*.pus2.auth0.com"`

As I understand it, the `sso.` might be problematic, I tried removing it inside `t1connection.js` and as I expected (but not wanted) I get the same response as when trying to manually get the token.

Thanks in advance for answering, let me know if there's anything more I can document to make it clearer.

**Comment by fsargent** [comment]
That's interesting. It should be https://auth.mediamath.com
I'll patch it. Sorry for the problem!

**Comment by fsargent** [comment]
Resolved in https://github.com/MediaMath/t1-node/commit/c9ffa29378b768d3c154058b6e966e597326c295
